In [1]:
import pandas as pd
from sklearn import  linear_model
import numpy as np
import matplotlib.pyplot as plt
import math
from sys import stdout

In [3]:
sales = pd.read_csv("kc_house_data.csv")
sales.head()


id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [4]:
train_data = pd.read_csv("kc_house_train_data.csv")
train_data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [5]:
test_data = pd.read_csv("kc_house_test_data.csv")

In [6]:
def get_numpy_data(data, features, output):

    #Adding a constant collumn with value 1 in the dataframe.
    data['constant'] = 1    
    #Adding the name of the constant collumn in the feature list.
    features = ['constant'] + features
    #Creating Feature matrix(Selecting columns and coverting to matrix).
    features_matrix=data[features].as_matrix()
    
    #Target collumn is converted to the numpy array
    output_array=np.array(data[output])
    return(features_matrix, output_array)

simple_features = ['sqft_living']
my_output= 'price'
get_numpy_data(train_data, simple_features, my_output)


(array([[   1, 1180],
        [   1, 2570],
        [   1,  770],
        ..., 
        [   1, 1530],
        [   1, 1600],
        [   1, 1020]]),
 array([ 221900.,  538000.,  180000., ...,  360000.,  400000.,  325000.]))

In [7]:
def predict_outcome(feature_matrix, weights):
    weights=np.array(weights)
    predictions = np.dot(feature_matrix, weights)
    
    return(predictions)


In [8]:
def feature_derivative(errors, feature):
    
    
    derivative = np.dot(2, np.dot(errors, feature))
    return derivative
                    
                        

In [12]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False
    weights = np.array(initial_weights)
   
    while not converged:
        # compute the predictions based on feature_matrix and weights:
        predictions = predict_outcome(feature_matrix, weights)
       
        # compute the errors as predictions - output:
        errors = predictions - output
        
        gradient_sum_squares = 0 # initialize the gradient
        
        
        
        
       
        # while not converged, update each weight individually:
        for i in range(len(weights)):
            # Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            # compute the derivative for weight[i]:
            
            derivative = feature_derivative(errors, feature_matrix[:,i])
            
            # add the squared derivative to the gradient magnitude
            gradient_sum_squares = gradient_sum_squares + derivative**2
            
            adjustment = step_size*derivative
            # update the weight based on step size and derivative:
            weights[i] =  weights[i] - adjustment
        gradient_magnitude = math.sqrt(gradient_sum_squares)
        stdout.write("\r%d" % int(gradient_magnitude))
        stdout.flush()
        if gradient_magnitude < tolerance:
            converged = True
    
    return(weights)

print regression_gradient_descent(simple_feature_matrix, output,initial_weights, step_size, tolerance)

18320017[-46999.88716555    281.91211918]


In [10]:
simple_features = ['sqft_living']
my_output= 'price'
simple_feature_matrix,output = get_numpy_data(train_data, simple_features, my_output)

initial_weights = np.array([-47000., 1.])

weights = np.array(initial_weights)
print weights
step_size = 7e-12
tolerance = 2.5e7

[ -4.70000000e+04   1.00000000e+00]


In [13]:
simple_weights = regression_gradient_descent(simple_feature_matrix, output,initial_weights, step_size, tolerance)
print simple_weights

18320017[-46999.88716555    281.91211918]


In [14]:
predict_outcome(simple_feature_matrix, simple_weights)

array([ 285656.4134612 ,  677514.25911474,  170072.44459936, ...,
        384325.65517252,  404059.50351479,  240550.47439317])